name: Update URIs and Create PR
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 on the first day of every month
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch used as target for automation'
        required: true
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest # using ubuntu as a lightweight environment
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.inputs.branchName }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run URI update script
      run: python taskcluster/scripts/uri_update.py

    - name: Check for changes
      id: git-check
      run: |
        if git diff --quiet; then
          echo "No changes detected, skipping PR creation."
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "Changes detected, proceeding to create PR."
          git diff
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated URI update"
          echo "changes_detected=true" >> $GITHUB_ENV
        fi

    - name: Create Pull Request
      if: env.changes_detected == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TEST_GITHUB_ACTION_TOKEN }}
        commit-message: Automated URI update
        title: Automated URI update on ${{ github.event.inputs.branchName || 'main' }}
        branch: auto-update-${{ github.run_number }}
        body: This automated PR updates the URIs.
